In [2]:
import pandas as pd
import librosa

In [3]:
original_df = pd.read_csv("../genres_v2.csv", low_memory=False)[["id", "genre"]]

In [4]:
original_df

id      genre
0      2Vc6NJ9PW9gD9q343XFRKx  Dark Trap
1      7pgJBLVz5VmnL7uGHmRj6p  Dark Trap
2      0vSWgAlfpye0WCGeNmuNhy  Dark Trap
3      0VSXnJqQkwuH2ei1nOQ1nu  Dark Trap
4      4jCeguq9rMTlbMmPHuO7S3  Dark Trap
...                       ...        ...
42300  46bXU7Sgj7104ZoXxzz9tM  hardstyle
42301  0he2ViGMUO3ajKTxLOfWVT  hardstyle
42302  72DAt9Lbpy9EUS29OzQLob  hardstyle
42303  6HXgExFVuE1c3cq9QjFCcU  hardstyle
42304  6MAAMZImxcvYhRnxDLTufD  hardstyle

[42305 rows x 2 columns]

In [5]:
import os

In [6]:
ids = []

for file in os.scandir(path="../tracks/"):
    ids += [file.name.replace(".mp3", "").split("_")[1]]

In [7]:
original_df.loc[original_df["id"].isin(ids)]

id            genre
1      7pgJBLVz5VmnL7uGHmRj6p        Dark Trap
13     1umsRbM7L4ju7rn9aU8Ju6        Dark Trap
33     2Tu4kHEeIVFn6Re2ybm2lQ        Dark Trap
106    6dCuGVBOQmVNEbRIDEUHy0        Dark Trap
120    4a9j7bIg4BT9J87pQT7b8j        Dark Trap
135    21cGO6AxAJJDTV7Po9ywZa        Dark Trap
189    6Ikh2kZIzZ2GEKpZfrV3D3        Dark Trap
193    0UzDPAMBI8miCHsYoqRb7g        Dark Trap
213    6aksxALGxEL6kOOvITALIm        Dark Trap
5168   2dPqNtgzsGdfvN9sw3Ot0f  Underground Rap
10576  4OmT5u1GqsK3Aa5YN15u2x       Trap Metal

In [8]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from tensorflow import keras
import librosa
import subprocess

In [9]:
for id in ids:
    print(id)

4OmT5u1GqsK3Aa5YN15u2x
2dPqNtgzsGdfvN9sw3Ot0f
21cGO6AxAJJDTV7Po9ywZa
6aksxALGxEL6kOOvITALIm
2Tu4kHEeIVFn6Re2ybm2lQ
0UzDPAMBI8miCHsYoqRb7g
7pgJBLVz5VmnL7uGHmRj6p
4a9j7bIg4BT9J87pQT7b8j
1umsRbM7L4ju7rn9aU8Ju6
6Ikh2kZIzZ2GEKpZfrV3D3
6dCuGVBOQmVNEbRIDEUHy0


In [10]:
full_data = []

for file in os.scandir("../tracks"):
    track = str(file).replace("<DirEntry '", "").replace("'>", "")
    data, sr = librosa.load(f"../tracks/{track}")
    full_data += [(data,sr)]

In [11]:
a = full_data[2][0]
len(a)

2695681

In [12]:
import numpy as np
np.var(librosa.feature.chroma_stft(y=a))

0.10242182

In [13]:
from sklearn.preprocessing import StandardScaler
fit = StandardScaler()

X = fit.fit_transform

 ## Features
    
1. Length
2. Chroma STFT (short-time Fourier transform) - Mean `np.mean(librosa.feature.chroma_stft(y = audio_timeseries))`
3. Chroma STFT (short-time Fourier transform) - Variance `np.var(librosa.feature.chroma_stft(y  =audio_timeseries))`
4. RMS - Mean - Compute root-mean-square (RMS) value for each frame then mean of that `np.mean(librosa.feature.rms(y = audio_timeseries))`
5. RMS - Variance - Compute root-mean-square (RMS) value for each frame then variance of that `np.var(librosa.feature.rms(y = audio_timeseries))`
6. Spectral centroid - Mean -  `np.mean(librosa.feature.rms(y = audio_timeseries))`
7. Spectral centroid - Variance -  `np.var(librosa.feature.rms(y = audio_timeseries))`

In [14]:
len(librosa.feature.tempogram(y=a))

384

In [16]:
librosa.feature.chroma_cens(y=a)

array([[0.8509567 , 0.8549814 , 0.8587386 , ..., 0.22822249, 0.2225654 ,
        0.21690479],
       [0.32244763, 0.31714746, 0.3118741 , ..., 0.27012098, 0.27052066,
        0.2708704 ],
       [0.20761602, 0.20058498, 0.19352236, ..., 0.37449574, 0.38193294,
        0.38923085],
       ...,
       [0.        , 0.        , 0.        , ..., 0.25852564, 0.25758284,
        0.25640512],
       [0.03817177, 0.03802476, 0.0377799 , ..., 0.40396982, 0.38772506,
        0.37093914],
       [0.29256797, 0.29731652, 0.30218646, ..., 0.22574437, 0.21847236,
        0.21138224]], dtype=float32)

In [ ]:
a

In [18]:
x = np.array([10.9, 4.5, 3.6, 70.8], dtype=float)
y = np.array([10.0, 6.5, 8.6, 1.8], dtype=float)
z = np.array([10.5, 5.5, 31.6, 7.8], dtype=float)

In [32]:
np.array([x,y,z])

array([[10.9,  4.5,  3.6, 70.8],
       [10. ,  6.5,  8.6,  1.8],
       [10.5,  5.5, 31.6,  7.8]])

In [28]:
from functools import reduce
from itertools import accumulate

In [31]:
list(accumulate([x,y,z]))

[array([10.9,  4.5,  3.6, 70.8]),
 array([20.9, 11. , 12.2, 72.6]),
 array([31.4, 16.5, 43.8, 80.4])]